// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: MicroR.jflex

/*Author: Suzanne Nolba*/


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class MICRORLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u1f00\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u0100\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u1f00\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u1f00\1\u4d00\1\u4e00"+
    "\1\u4f00\1\u1f00\3\u0100\1\u5000\1\u5100\1\u5200\12\u1f00\4\u0100"+
    "\1\u5300\17\u1f00\2\u0100\1\u5400\41\u1f00\2\u0100\1\u5500\1\u5600"+
    "\2\u1f00\1\u5700\1\u5800\27\u0100\1\u5900\2\u0100\1\u5a00\45\u1f00"+
    "\1\u0100\1\u5b00\1\u5c00\11\u1f00\1\u5d00\27\u1f00\1\u5e00\1\u5f00"+
    "\1\u6000\1\u6100\11\u1f00\1\u6200\1\u6300\5\u1f00\1\u6400\1\u6500"+
    "\4\u1f00\1\u6600\21\u1f00\246\u0100\1\u6700\20\u0100\1\u6800\1\u6900"+
    "\25\u0100\1\u6a00\34\u0100\1\u6b00\14\u1f00\2\u0100\1\u6c00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\3\3\22\0\1\1\1\4\1\5"+
    "\1\6\2\0\1\7\1\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\12\20\1\21\1\22\1\23"+
    "\1\24\1\25\2\0\13\26\1\27\5\26\1\30\10\26"+
    "\4\0\1\31\1\0\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\2\26\1\43\1\44\1\45"+
    "\1\46\1\47\1\26\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\3\26\1\56\1\0\1\57\7\0\1\3\44\0"+
    "\1\26\12\0\1\26\4\0\1\26\5\0\27\26\1\0"+
    "\37\26\1\0\u01ca\26\4\0\14\26\16\0\5\26\7\0"+
    "\1\26\1\0\1\26\201\0\5\26\1\0\2\26\2\0"+
    "\4\26\1\0\1\26\6\0\1\26\1\0\3\26\1\0"+
    "\1\26\1\0\24\26\1\0\123\26\1\0\213\26\10\0"+
    "\246\26\1\0\46\26\2\0\1\26\6\0\51\26\107\0"+
    "\33\26\4\0\4\26\55\0\53\26\25\0\12\20\4\0"+
    "\2\26\1\0\143\26\1\0\1\26\17\0\2\26\7\0"+
    "\2\26\12\20\3\26\2\0\1\26\20\0\1\26\1\0"+
    "\36\26\35\0\131\26\13\0\1\26\16\0\12\20\41\26"+
    "\11\0\2\26\4\0\1\26\5\0\26\26\4\0\1\26"+
    "\11\0\1\26\3\0\1\26\27\0\31\26\7\0\13\26"+
    "\65\0\25\26\1\0\10\26\106\0\66\26\3\0\1\26"+
    "\22\0\1\26\7\0\12\26\4\0\12\20\1\0\20\26"+
    "\4\0\10\26\2\0\2\26\2\0\26\26\1\0\7\26"+
    "\1\0\1\26\3\0\4\26\3\0\1\26\20\0\1\26"+
    "\15\0\2\26\1\0\3\26\4\0\12\20\2\26\12\0"+
    "\1\26\10\0\6\26\4\0\2\26\2\0\26\26\1\0"+
    "\7\26\1\0\2\26\1\0\2\26\1\0\2\26\37\0"+
    "\4\26\1\0\1\26\7\0\12\20\2\0\3\26\20\0"+
    "\11\26\1\0\3\26\1\0\26\26\1\0\7\26\1\0"+
    "\2\26\1\0\5\26\3\0\1\26\22\0\1\26\17\0"+
    "\2\26\4\0\12\20\11\0\1\26\13\0\10\26\2\0"+
    "\2\26\2\0\26\26\1\0\7\26\1\0\2\26\1\0"+
    "\5\26\3\0\1\26\36\0\2\26\1\0\3\26\4\0"+
    "\12\20\1\0\1\26\21\0\1\26\1\0\6\26\3\0"+
    "\3\26\1\0\4\26\3\0\2\26\1\0\1\26\1\0"+
    "\2\26\3\0\2\26\3\0\3\26\3\0\14\26\26\0"+
    "\1\26\25\0\12\20\25\0\10\26\1\0\3\26\1\0"+
    "\27\26\1\0\20\26\3\0\1\26\32\0\3\26\5\0"+
    "\2\26\4\0\12\20\20\0\1\26\4\0\10\26\1\0"+
    "\3\26\1\0\27\26\1\0\12\26\1\0\5\26\3\0"+
    "\1\26\40\0\1\26\1\0\2\26\4\0\12\20\1\0"+
    "\2\26\22\0\10\26\1\0\3\26\1\0\51\26\2\0"+
    "\1\26\20\0\1\26\5\0\3\26\10\0\3\26\4\0"+
    "\12\20\12\0\6\26\5\0\22\26\3\0\30\26\1\0"+
    "\11\26\1\0\1\26\2\0\7\26\37\0\12\20\21\0"+
    "\60\26\1\0\2\26\14\0\7\26\11\0\12\20\47\0"+
    "\2\26\1\0\1\26\1\0\5\26\1\0\30\26\1\0"+
    "\1\26\1\0\12\26\1\0\2\26\11\0\1\26\2\0"+
    "\5\26\1\0\1\26\11\0\12\20\2\0\4\26\40\0"+
    "\1\26\37\0\12\20\26\0\10\26\1\0\44\26\33\0"+
    "\5\26\163\0\53\26\24\0\1\26\12\20\6\0\6\26"+
    "\4\0\4\26\3\0\1\26\3\0\2\26\7\0\3\26"+
    "\4\0\15\26\14\0\1\26\1\0\12\20\6\0\46\26"+
    "\1\0\1\26\5\0\1\26\2\0\53\26\1\0\115\26"+
    "\1\0\4\26\2\0\7\26\1\0\1\26\1\0\4\26"+
    "\2\0\51\26\1\0\4\26\2\0\41\26\1\0\4\26"+
    "\2\0\7\26\1\0\1\26\1\0\4\26\2\0\17\26"+
    "\1\0\71\26\1\0\4\26\2\0\103\26\45\0\20\26"+
    "\20\0\126\26\2\0\6\26\3\0\u016c\26\2\0\21\26"+
    "\1\0\32\26\5\0\113\26\6\0\10\26\7\0\15\26"+
    "\1\0\4\26\16\0\22\26\16\0\22\26\16\0\15\26"+
    "\1\0\3\26\17\0\64\26\43\0\1\26\4\0\1\26"+
    "\3\0\12\20\46\0\12\20\6\0\131\26\7\0\5\26"+
    "\2\0\42\26\1\0\1\26\5\0\106\26\12\0\37\26"+
    "\47\0\12\20\36\26\2\0\5\26\13\0\54\26\4\0"+
    "\32\26\6\0\12\20\46\0\27\26\11\0\65\26\53\0"+
    "\12\20\6\0\12\20\15\0\1\26\135\0\57\26\21\0"+
    "\7\26\4\0\12\20\51\0\36\26\15\0\2\26\12\20"+
    "\54\26\32\0\44\26\34\0\12\20\3\0\3\26\12\20"+
    "\44\26\2\0\11\26\7\0\53\26\2\0\3\26\51\0"+
    "\4\26\1\0\6\26\1\0\2\26\3\0\1\26\5\0"+
    "\300\26\100\0\26\26\2\0\6\26\2\0\46\26\2\0"+
    "\6\26\2\0\10\26\1\0\1\26\1\0\1\26\1\0"+
    "\1\26\1\0\37\26\2\0\65\26\1\0\7\26\1\0"+
    "\1\26\3\0\3\26\1\0\7\26\3\0\4\26\2\0"+
    "\6\26\4\0\15\26\5\0\3\26\1\0\7\26\53\0"+
    "\2\3\107\0\1\26\15\0\1\26\20\0\15\26\145\0"+
    "\1\26\4\0\1\26\2\0\12\26\1\0\1\26\3\0"+
    "\5\26\6\0\1\26\1\0\1\26\1\0\1\26\1\0"+
    "\4\26\1\0\13\26\2\0\4\26\5\0\5\26\4\0"+
    "\1\26\64\0\2\26\u017b\0\57\26\1\0\57\26\1\0"+
    "\205\26\6\0\4\26\3\0\2\26\14\0\46\26\1\0"+
    "\1\26\5\0\1\26\2\0\70\26\7\0\1\26\20\0"+
    "\27\26\11\0\7\26\1\0\7\26\1\0\7\26\1\0"+
    "\7\26\1\0\7\26\1\0\7\26\1\0\7\26\1\0"+
    "\7\26\120\0\1\26\325\0\2\26\52\0\5\26\5\0"+
    "\2\26\4\0\126\26\6\0\3\26\1\0\132\26\1\0"+
    "\4\26\5\0\53\26\1\0\136\26\21\0\33\26\65\0"+
    "\306\26\112\0\360\26\20\0\215\26\103\0\56\26\2\0"+
    "\15\26\3\0\20\26\12\20\2\26\24\0\57\26\20\0"+
    "\37\26\2\0\106\26\61\0\11\26\2\0\147\26\2\0"+
    "\65\26\2\0\5\26\60\0\13\26\1\0\3\26\1\0"+
    "\4\26\1\0\27\26\35\0\64\26\16\0\62\26\34\0"+
    "\12\20\30\0\6\26\3\0\1\26\1\0\2\26\1\0"+
    "\12\20\34\26\12\0\27\26\31\0\35\26\7\0\57\26"+
    "\34\0\1\26\12\20\6\0\5\26\1\0\12\26\12\20"+
    "\5\26\1\0\51\26\27\0\3\26\1\0\10\26\4\0"+
    "\12\20\6\0\27\26\3\0\1\26\3\0\62\26\1\0"+
    "\1\26\3\0\2\26\2\0\5\26\2\0\1\26\1\0"+
    "\1\26\30\0\3\26\2\0\13\26\7\0\3\26\14\0"+
    "\6\26\2\0\6\26\2\0\6\26\11\0\7\26\1\0"+
    "\7\26\1\0\53\26\1\0\14\26\10\0\163\26\15\0"+
    "\12\20\6\0\244\26\14\0\27\26\4\0\61\26\4\0"+
    "\u0100\3\156\26\2\0\152\26\46\0\7\26\14\0\5\26"+
    "\5\0\1\26\1\0\12\26\1\0\15\26\1\0\5\26"+
    "\1\0\1\26\1\0\2\26\1\0\2\26\1\0\154\26"+
    "\41\0\153\26\22\0\100\26\2\0\66\26\50\0\14\26"+
    "\164\0\5\26\1\0\207\26\23\0\12\20\7\0\32\26"+
    "\6\0\32\26\13\0\131\26\3\0\6\26\2\0\6\26"+
    "\2\0\6\26\2\0\3\26\43\0\14\26\1\0\32\26"+
    "\1\0\23\26\1\0\2\26\1\0\17\26\2\0\16\26"+
    "\42\0\173\26\205\0\35\26\3\0\61\26\57\0\40\26"+
    "\15\0\24\26\1\0\10\26\6\0\46\26\12\0\36\26"+
    "\2\0\44\26\4\0\10\26\60\0\236\26\2\0\12\20"+
    "\6\0\44\26\4\0\44\26\4\0\50\26\10\0\64\26"+
    "\234\0\67\26\11\0\26\26\12\0\10\26\230\0\6\26"+
    "\2\0\1\26\1\0\54\26\1\0\2\26\3\0\1\26"+
    "\2\0\27\26\12\0\27\26\11\0\37\26\101\0\23\26"+
    "\1\0\2\26\12\0\26\26\12\0\32\26\106\0\70\26"+
    "\6\0\2\26\100\0\1\26\17\0\4\26\1\0\3\26"+
    "\1\0\35\26\52\0\35\26\3\0\35\26\43\0\10\26"+
    "\1\0\34\26\33\0\66\26\12\0\26\26\12\0\23\26"+
    "\15\0\22\26\156\0\111\26\67\0\63\26\15\0\63\26"+
    "\15\0\44\26\14\0\12\20\306\0\35\26\12\0\1\26"+
    "\10\0\26\26\232\0\27\26\14\0\65\26\56\0\12\20"+
    "\23\0\55\26\40\0\31\26\7\0\12\20\11\0\44\26"+
    "\17\0\12\20\4\0\1\26\13\0\43\26\3\0\1\26"+
    "\14\0\60\26\16\0\4\26\13\0\12\20\1\26\1\0"+
    "\1\26\43\0\22\26\1\0\31\26\124\0\7\26\1\0"+
    "\1\26\1\0\4\26\1\0\17\26\1\0\12\26\7\0"+
    "\57\26\21\0\12\20\13\0\10\26\2\0\2\26\2\0"+
    "\26\26\1\0\7\26\1\0\2\26\1\0\5\26\3\0"+
    "\1\26\22\0\1\26\14\0\5\26\236\0\65\26\22\0"+
    "\4\26\5\0\12\20\5\0\1\26\40\0\60\26\24\0"+
    "\2\26\1\0\1\26\10\0\12\20\246\0\57\26\51\0"+
    "\4\26\44\0\60\26\24\0\1\26\13\0\12\20\46\0"+
    "\53\26\15\0\1\26\7\0\12\20\66\0\33\26\25\0"+
    "\12\20\306\0\54\26\164\0\100\26\12\20\25\0\1\26"+
    "\240\0\10\26\2\0\47\26\20\0\1\26\1\0\1\26"+
    "\34\0\1\26\12\0\50\26\7\0\1\26\25\0\1\26"+
    "\13\0\56\26\23\0\1\26\42\0\71\26\7\0\11\26"+
    "\1\0\45\26\21\0\1\26\17\0\12\20\30\0\36\26"+
    "\160\0\7\26\1\0\2\26\1\0\46\26\25\0\1\26"+
    "\11\0\12\20\6\0\6\26\1\0\2\26\1\0\40\26"+
    "\16\0\1\26\7\0\12\20\u0136\0\23\26\15\0\232\26"+
    "\346\0\304\26\274\0\57\26\321\0\107\26\271\0\71\26"+
    "\7\0\37\26\1\0\12\20\146\0\36\26\22\0\60\26"+
    "\20\0\4\26\14\0\12\20\11\0\25\26\5\0\23\26"+
    "\260\0\100\26\200\0\113\26\5\0\1\26\102\0\15\26"+
    "\100\0\2\26\1\0\1\26\34\0\370\26\10\0\363\26"+
    "\15\0\37\26\61\0\3\26\21\0\4\26\10\0\u018c\26"+
    "\4\0\153\26\5\0\15\26\3\0\11\26\7\0\12\26"+
    "\146\0\125\26\1\0\107\26\1\0\2\26\2\0\1\26"+
    "\2\0\2\26\2\0\4\26\1\0\14\26\1\0\1\26"+
    "\1\0\7\26\1\0\101\26\1\0\4\26\2\0\10\26"+
    "\1\0\7\26\1\0\34\26\1\0\4\26\1\0\5\26"+
    "\1\0\1\26\3\0\7\26\1\0\u0154\26\2\0\31\26"+
    "\1\0\31\26\1\0\37\26\1\0\31\26\1\0\37\26"+
    "\1\0\31\26\1\0\37\26\1\0\31\26\1\0\37\26"+
    "\1\0\31\26\1\0\10\26\2\0\62\20\55\26\12\0"+
    "\7\26\2\0\12\20\4\0\1\26\u0171\0\54\26\4\0"+
    "\12\20\6\0\305\26\73\0\104\26\7\0\1\26\4\0"+
    "\12\20\246\0\4\26\1\0\33\26\1\0\2\26\1\0"+
    "\1\26\2\0\1\26\1\0\12\26\1\0\4\26\1\0"+
    "\1\26\1\0\1\26\6\0\1\26\4\0\1\26\1\0"+
    "\1\26\1\0\1\26\1\0\3\26\1\0\2\26\1\0"+
    "\1\26\2\0\1\26\1\0\1\26\1\0\1\26\1\0"+
    "\1\26\1\0\1\26\1\0\2\26\1\0\1\26\2\0"+
    "\4\26\1\0\7\26\1\0\4\26\1\0\4\26\1\0"+
    "\1\26\1\0\12\26\1\0\21\26\5\0\3\26\1\0"+
    "\5\26\1\0\21\26\104\0\327\26\51\0\65\26\13\0"+
    "\336\26\2\0\u0182\26\16\0\u0131\26\37\0\36\26\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27904];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\2\1\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\1\1\15\1\16\1\17\1\20\22\21\1\22\1\23"+
    "\1\0\1\24\1\25\1\26\1\27\1\30\1\21\1\0"+
    "\4\21\1\31\4\21\1\32\12\21\1\0\1\21\1\0"+
    "\1\33\1\0\1\21\1\0\4\21\1\34\4\21\1\35"+
    "\6\21\1\36\1\21\1\0\1\21\1\0\1\33\1\0"+
    "\1\21\1\33\1\21\1\37\1\40\1\41\1\21\1\42"+
    "\1\43\1\44\4\21\1\45\1\46\1\21\1\0\1\21"+
    "\1\0\1\33\1\0\1\21\1\33\1\47\1\50\1\21"+
    "\1\51\3\21\1\52\1\0\1\21\1\0\1\33\1\0"+
    "\1\21\1\33\3\21\1\53\1\0\1\21\1\0\1\33"+
    "\1\0\1\21\1\33\3\21\1\54\1\21\1\0\1\33"+
    "\1\0\1\21\1\33\1\55\1\21\1\56\1\21\1\0"+
    "\1\33\1\0\1\21\1\33\1\57\1\21\1\0\1\33"+
    "\3\60\1\21\1\0\1\33\1\21\1\0\1\33\1\21"+
    "\1\0\1\33\1\21\1\0\1\33\1\21\1\0\1\33"+
    "\1\21\1\0\1\33\1\21\1\0\1\33\1\21\1\0"+
    "\1\33\1\21\1\0\1\33\1\21\1\0\1\33\1\21"+
    "\1\0\1\33\1\21\1\0\1\33\1\21\1\0\1\33"+
    "\1\21\1\0\1\33\1\21\1\0\1\33\1\21\1\0"+
    "\1\33\1\21\1\0\1\33\1\21\1\0\1\33\1\21"+
    "\1\0\1\33\1\21\1\0\1\33\1\21\1\0\2\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[239];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\60\0\60\0\140\0\220\0\300\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\60\0\60\0\360"+
    "\0\u0120\0\60\0\u0150\0\60\0\u0180\0\u01b0\0\u01e0\0\u0210"+
    "\0\u0240\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390"+
    "\0\u03c0\0\u03f0\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\60"+
    "\0\60\0\u0510\0\60\0\60\0\60\0\60\0\60\0\u0540"+
    "\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0540\0\u0660\0\u0690"+
    "\0\u06c0\0\u06f0\0\u0540\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0"+
    "\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960"+
    "\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0"+
    "\0\u0930\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0930\0\u0bd0\0\u0c00"+
    "\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0930\0\u0cf0\0\u0d20\0\u0d50"+
    "\0\u0d80\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0d50\0\u0ea0"+
    "\0\u0d50\0\u0ed0\0\u0d50\0\u0d50\0\u0d50\0\u0f00\0\u0f30\0\u0f60"+
    "\0\u0f90\0\u0d50\0\u0d50\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\u1080"+
    "\0\u10b0\0\u10e0\0\u1110\0\u1020\0\u1020\0\u1140\0\u1020\0\u1170"+
    "\0\u11a0\0\u11d0\0\u1020\0\u1200\0\u1230\0\u1260\0\u1290\0\u12c0"+
    "\0\u12f0\0\u1320\0\u1350\0\u1380\0\u13b0\0\u1230\0\u13e0\0\u1410"+
    "\0\u1440\0\u1470\0\u14a0\0\u14d0\0\u1500\0\u1530\0\u1560\0\u1590"+
    "\0\60\0\u15c0\0\u15f0\0\u1620\0\u1650\0\u1680\0\u16b0\0\u15c0"+
    "\0\u16e0\0\u15c0\0\u1710\0\u1740\0\u1770\0\u17a0\0\u17d0\0\u1800"+
    "\0\u1710\0\u1830\0\u1860\0\u1890\0\60\0\u1830\0\u1890\0\u18c0"+
    "\0\u18f0\0\u1920\0\u1950\0\u1980\0\u19b0\0\u19e0\0\u1a10\0\u1a40"+
    "\0\u1a70\0\u1aa0\0\u1ad0\0\u1b00\0\u1b30\0\u1b60\0\u1b90\0\u1bc0"+
    "\0\u1bf0\0\u1c20\0\u1c50\0\u1c80\0\u1cb0\0\u1ce0\0\u1d10\0\u1d40"+
    "\0\u1d70\0\u1da0\0\u1dd0\0\u1e00\0\u1e30\0\u1e60\0\u1e90\0\u1ec0"+
    "\0\u1ef0\0\u1f20\0\u1f50\0\u1f80\0\u1fb0\0\u1fe0\0\u2010\0\u2040"+
    "\0\u2070\0\u20a0\0\u20d0\0\u2100\0\u2130\0\u2160\0\u2190\0\u21c0"+
    "\0\u21f0\0\u2220\0\u2250\0\u2280\0\u22b0\0\u22e0\0\u2310\0\u2340"+
    "\0\u2370\0\u23a0\0\u23d0\0\u2400\0\u2430\0\u2460\0\u2430";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[239];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\3\26\1\2\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\26\1\35\1\36"+
    "\1\26\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\26\1\46\1\47\1\50\1\51\107\0\1\52\30\0"+
    "\2\6\1\0\55\6\7\0\1\53\70\0\1\20\63\0"+
    "\1\54\57\0\1\55\1\56\56\0\1\57\53\0\1\60"+
    "\5\0\3\60\1\61\24\60\22\0\1\60\5\0\3\60"+
    "\1\61\17\60\1\62\4\60\22\0\1\60\5\0\3\60"+
    "\1\61\4\60\1\63\17\60\22\0\1\60\5\0\3\60"+
    "\1\61\1\64\13\60\1\65\7\60\22\0\1\60\5\0"+
    "\3\60\1\61\14\60\1\66\7\60\22\0\1\60\5\0"+
    "\3\60\1\61\11\60\1\67\1\60\1\70\10\60\22\0"+
    "\1\60\5\0\3\60\1\61\21\60\1\71\2\60\22\0"+
    "\1\60\5\0\3\60\1\61\4\60\1\72\17\60\22\0"+
    "\1\60\5\0\3\60\1\61\5\60\1\73\16\60\22\0"+
    "\1\60\5\0\3\60\1\61\1\74\23\60\22\0\1\60"+
    "\5\0\3\60\1\61\21\60\1\75\2\60\22\0\1\60"+
    "\5\0\3\60\1\61\3\60\1\76\20\60\22\0\1\60"+
    "\5\0\3\60\1\61\16\60\1\77\5\60\22\0\1\60"+
    "\5\0\3\60\1\61\4\60\1\100\17\60\22\0\1\60"+
    "\5\0\3\60\1\61\14\60\1\101\7\60\22\0\1\60"+
    "\5\0\3\60\1\61\1\102\6\60\1\103\14\60\22\0"+
    "\1\60\5\0\3\60\1\61\1\104\23\60\22\0\1\60"+
    "\5\0\3\60\1\61\7\60\1\105\14\60\44\0\1\106"+
    "\35\0\1\107\5\0\3\107\1\110\24\107\22\0\1\111"+
    "\5\0\3\111\1\0\24\111\2\0\2\112\2\0\14\112"+
    "\1\113\5\112\3\113\1\114\24\113\2\112\20\0\1\107"+
    "\5\0\3\107\1\110\6\107\1\115\15\107\22\0\1\107"+
    "\5\0\3\107\1\110\11\107\1\116\12\107\22\0\1\107"+
    "\5\0\3\107\1\110\13\107\1\117\10\107\22\0\1\107"+
    "\5\0\3\107\1\110\17\107\1\120\4\107\22\0\1\107"+
    "\5\0\3\107\1\110\3\107\1\121\20\107\22\0\1\107"+
    "\5\0\3\107\1\110\13\107\1\122\10\107\22\0\1\107"+
    "\5\0\3\107\1\110\1\123\23\107\22\0\1\107\5\0"+
    "\3\107\1\110\10\107\1\124\13\107\22\0\1\107\5\0"+
    "\3\107\1\110\11\107\1\125\12\107\22\0\1\107\5\0"+
    "\3\107\1\110\3\107\1\126\20\107\22\0\1\107\5\0"+
    "\3\107\1\110\10\107\1\127\3\107\1\130\7\107\22\0"+
    "\1\107\5\0\3\107\1\110\1\131\23\107\22\0\1\107"+
    "\5\0\3\107\1\110\21\107\1\132\2\107\22\0\1\107"+
    "\5\0\3\107\1\110\10\107\1\133\13\107\22\0\1\107"+
    "\5\0\3\107\1\110\4\107\1\134\17\107\22\0\1\107"+
    "\5\0\3\107\1\110\16\107\1\135\5\107\22\0\1\107"+
    "\5\0\3\107\1\110\10\107\1\136\13\107\53\0\1\137"+
    "\26\0\1\140\5\0\3\140\1\141\24\140\22\0\1\142"+
    "\5\0\3\142\1\0\24\142\22\0\1\142\5\0\3\142"+
    "\1\110\24\142\44\0\1\143\35\0\1\140\5\0\3\140"+
    "\1\141\10\140\1\144\13\140\22\0\1\142\5\0\3\142"+
    "\1\0\10\142\1\145\13\142\22\0\1\140\5\0\3\140"+
    "\1\141\10\140\1\146\13\140\22\0\1\140\5\0\3\140"+
    "\1\141\11\140\1\147\12\140\22\0\1\140\5\0\3\140"+
    "\1\141\17\140\1\150\4\140\22\0\1\140\5\0\3\140"+
    "\1\141\4\140\1\151\17\140\22\0\1\140\5\0\3\140"+
    "\1\141\2\140\1\152\21\140\22\0\1\140\5\0\3\140"+
    "\1\141\3\140\1\153\20\140\22\0\1\140\5\0\3\140"+
    "\1\141\13\140\1\154\10\140\22\0\1\140\5\0\3\140"+
    "\1\141\11\140\1\155\12\140\22\0\1\140\5\0\3\140"+
    "\1\141\13\140\1\156\10\140\22\0\1\140\5\0\3\140"+
    "\1\141\2\140\1\157\21\140\22\0\1\140\5\0\3\140"+
    "\1\141\3\140\1\160\20\140\22\0\1\140\5\0\3\140"+
    "\1\141\16\140\1\161\5\140\22\0\1\140\5\0\3\140"+
    "\1\141\11\140\1\162\12\140\22\0\1\140\5\0\3\140"+
    "\1\141\13\140\1\163\10\140\22\0\1\140\5\0\3\140"+
    "\1\141\11\140\1\164\12\140\54\0\1\165\25\0\1\166"+
    "\5\0\3\166\1\167\24\166\22\0\1\170\5\0\3\170"+
    "\1\0\24\170\22\0\1\170\5\0\3\170\1\141\24\170"+
    "\47\0\1\171\32\0\1\166\5\0\3\166\1\167\13\166"+
    "\1\172\10\166\22\0\1\170\5\0\3\170\1\141\13\170"+
    "\1\173\10\170\22\0\1\166\5\0\3\166\1\167\13\166"+
    "\1\174\10\166\22\0\1\166\5\0\3\166\1\167\20\166"+
    "\1\175\3\166\22\0\1\166\5\0\3\166\1\167\20\166"+
    "\1\176\3\166\22\0\1\166\5\0\3\166\1\167\20\166"+
    "\1\177\3\166\22\0\1\166\5\0\3\166\1\167\4\166"+
    "\1\200\17\166\22\0\1\166\5\0\3\166\1\167\11\166"+
    "\1\201\12\166\22\0\1\166\5\0\3\166\1\167\2\166"+
    "\1\202\21\166\22\0\1\166\5\0\3\166\1\167\4\166"+
    "\1\203\17\166\2\0\2\204\2\0\54\204\20\0\1\205"+
    "\5\0\3\205\1\206\24\205\22\0\1\207\5\0\3\207"+
    "\1\0\24\207\22\0\1\207\5\0\3\207\1\167\24\207"+
    "\54\0\1\210\25\0\1\205\5\0\3\205\1\206\20\205"+
    "\1\211\3\205\22\0\1\207\5\0\3\207\1\167\20\207"+
    "\1\212\3\207\22\0\1\205\5\0\3\205\1\206\10\205"+
    "\1\213\13\205\22\0\1\205\5\0\3\205\1\206\3\205"+
    "\1\214\20\205\22\0\1\205\5\0\3\205\1\206\10\205"+
    "\1\215\13\205\22\0\1\205\5\0\3\205\1\206\4\205"+
    "\1\216\17\205\32\0\1\217\47\0\1\220\5\0\3\220"+
    "\1\221\24\220\22\0\1\222\5\0\3\222\1\0\24\222"+
    "\22\0\1\222\5\0\3\222\1\206\24\222\40\0\1\223"+
    "\41\0\1\220\5\0\3\220\1\221\4\220\1\224\17\220"+
    "\22\0\1\222\5\0\3\222\1\206\4\222\1\225\17\222"+
    "\22\0\1\220\5\0\3\220\1\221\14\220\1\226\7\220"+
    "\22\0\1\220\5\0\3\220\1\221\21\220\1\227\2\220"+
    "\22\0\1\220\5\0\3\220\1\221\13\220\1\230\10\220"+
    "\7\0\1\231\72\0\1\232\5\0\3\232\1\233\24\232"+
    "\22\0\1\234\5\0\3\234\1\0\24\234\22\0\1\234"+
    "\5\0\3\234\1\221\24\234\42\0\1\235\37\0\1\232"+
    "\5\0\3\232\1\233\6\232\1\236\15\232\22\0\1\234"+
    "\5\0\3\234\1\221\6\234\1\237\15\234\22\0\1\232"+
    "\5\0\3\232\1\233\13\232\1\240\10\232\22\0\1\232"+
    "\5\0\3\232\1\233\16\232\1\241\5\232\22\0\1\232"+
    "\5\0\3\232\1\233\4\232\1\242\17\232\22\0\1\243"+
    "\5\0\3\243\1\244\24\243\22\0\1\245\5\0\3\245"+
    "\1\0\24\245\22\0\1\245\5\0\3\245\1\233\24\245"+
    "\40\0\1\246\41\0\1\243\5\0\3\243\1\244\4\243"+
    "\1\247\17\243\22\0\1\245\5\0\3\245\1\233\4\245"+
    "\1\250\17\245\22\0\1\243\5\0\3\243\1\244\4\243"+
    "\1\251\17\243\22\0\1\252\5\0\3\252\1\253\24\252"+
    "\22\0\1\254\5\0\3\254\1\0\24\254\22\0\1\254"+
    "\5\0\3\254\1\244\24\254\52\0\1\255\27\0\1\252"+
    "\5\0\3\252\1\253\16\252\1\256\5\252\22\0\1\254"+
    "\5\0\3\254\1\244\16\254\1\257\5\254\22\0\1\260"+
    "\5\0\3\260\1\261\24\260\22\0\1\262\5\0\3\262"+
    "\1\0\24\262\22\0\1\262\5\0\3\262\1\253\24\262"+
    "\22\0\1\263\5\0\3\263\1\264\24\263\22\0\1\265"+
    "\5\0\3\265\1\0\24\265\22\0\1\265\5\0\3\265"+
    "\1\261\24\265\22\0\1\266\5\0\3\266\1\267\24\266"+
    "\22\0\1\270\5\0\3\270\1\0\24\270\22\0\1\270"+
    "\5\0\3\270\1\264\24\270\22\0\1\271\5\0\3\271"+
    "\1\272\24\271\22\0\1\273\5\0\3\273\1\0\24\273"+
    "\22\0\1\273\5\0\3\273\1\267\24\273\22\0\1\274"+
    "\5\0\3\274\1\275\24\274\22\0\1\276\5\0\3\276"+
    "\1\0\24\276\22\0\1\276\5\0\3\276\1\272\24\276"+
    "\22\0\1\277\5\0\3\277\1\300\24\277\22\0\1\301"+
    "\5\0\3\301\1\0\24\301\22\0\1\301\5\0\3\301"+
    "\1\275\24\301\22\0\1\302\5\0\3\302\1\303\24\302"+
    "\22\0\1\304\5\0\3\304\1\0\24\304\22\0\1\304"+
    "\5\0\3\304\1\300\24\304\22\0\1\305\5\0\3\305"+
    "\1\306\24\305\22\0\1\307\5\0\3\307\1\0\24\307"+
    "\22\0\1\307\5\0\3\307\1\303\24\307\22\0\1\310"+
    "\5\0\3\310\1\311\24\310\22\0\1\312\5\0\3\312"+
    "\1\0\24\312\22\0\1\312\5\0\3\312\1\306\24\312"+
    "\22\0\1\313\5\0\3\313\1\314\24\313\22\0\1\315"+
    "\5\0\3\315\1\0\24\315\22\0\1\315\5\0\3\315"+
    "\1\311\24\315\22\0\1\316\5\0\3\316\1\317\24\316"+
    "\22\0\1\320\5\0\3\320\1\0\24\320\22\0\1\320"+
    "\5\0\3\320\1\314\24\320\22\0\1\321\5\0\3\321"+
    "\1\322\24\321\22\0\1\323\5\0\3\323\1\0\24\323"+
    "\22\0\1\323\5\0\3\323\1\317\24\323\22\0\1\324"+
    "\5\0\3\324\1\325\24\324\22\0\1\326\5\0\3\326"+
    "\1\0\24\326\22\0\1\326\5\0\3\326\1\322\24\326"+
    "\22\0\1\327\5\0\3\327\1\330\24\327\22\0\1\331"+
    "\5\0\3\331\1\0\24\331\22\0\1\331\5\0\3\331"+
    "\1\325\24\331\22\0\1\332\5\0\3\332\1\333\24\332"+
    "\22\0\1\334\5\0\3\334\1\0\24\334\22\0\1\334"+
    "\5\0\3\334\1\330\24\334\22\0\1\335\5\0\3\335"+
    "\1\336\24\335\22\0\1\337\5\0\3\337\1\0\24\337"+
    "\22\0\1\337\5\0\3\337\1\333\24\337\22\0\1\340"+
    "\5\0\3\340\1\341\24\340\22\0\1\342\5\0\3\342"+
    "\1\0\24\342\22\0\1\342\5\0\3\342\1\336\24\342"+
    "\22\0\1\343\5\0\3\343\1\344\24\343\22\0\1\345"+
    "\5\0\3\345\1\0\24\345\22\0\1\345\5\0\3\345"+
    "\1\341\24\345\22\0\1\346\5\0\3\346\1\347\24\346"+
    "\22\0\1\350\5\0\3\350\1\0\24\350\22\0\1\350"+
    "\5\0\3\350\1\344\24\350\22\0\1\351\5\0\3\351"+
    "\1\352\24\351\22\0\1\353\5\0\3\353\1\0\24\353"+
    "\22\0\1\353\5\0\3\353\1\347\24\353\22\0\1\354"+
    "\5\0\3\354\1\355\24\354\22\0\1\356\5\0\3\356"+
    "\1\0\24\356\22\0\1\356\5\0\3\356\1\352\24\356"+
    "\22\0\1\354\5\0\3\354\1\0\24\354\22\0\1\357"+
    "\5\0\3\357\1\0\24\357\22\0\1\357\5\0\3\357"+
    "\1\355\24\357\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9360];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\3\1\10\11\2\1\1\11\1\1\1\11"+
    "\23\1\2\11\1\0\5\11\1\1\1\0\24\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\22\1\1\0"+
    "\1\1\1\0\1\1\1\0\21\1\1\0\1\1\1\0"+
    "\1\1\1\0\12\1\1\0\1\1\1\0\1\1\1\0"+
    "\6\1\1\0\1\1\1\0\1\1\1\0\5\1\1\11"+
    "\1\1\1\0\1\1\1\0\6\1\1\0\1\1\1\0"+
    "\4\1\1\0\1\1\1\11\3\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[239];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	private void echo () { System . out . print (yytext ()); }
	
	public int position () { return yycolumn; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MICRORLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	{ return new Token (Symbol . EOF); }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { echo (); ErrorMessage . print (yycolumn, "Illegal character");
            }
            // fall through
          case 49: break;
          case 2:
            { echo ();
            }
            // fall through
          case 50: break;
          case 3:
            { echo (); return new Token( Symbol . RELOPE);
            }
            // fall through
          case 51: break;
          case 4:
            { echo (); return new Token (Symbol . LPAREN);
            }
            // fall through
          case 52: break;
          case 5:
            { echo (); return new Token (Symbol . RPAREN);
            }
            // fall through
          case 53: break;
          case 6:
            { echo (); return new Token (Symbol . TIMES);
            }
            // fall through
          case 54: break;
          case 7:
            { echo (); return new Token (Symbol . PLUS);
            }
            // fall through
          case 55: break;
          case 8:
            { echo (); return new Token (Symbol . COMMA);
            }
            // fall through
          case 56: break;
          case 9:
            { echo (); return new Token (Symbol . MINUS);
            }
            // fall through
          case 57: break;
          case 10:
            { echo (); return new Token (Symbol . PERIOD);
            }
            // fall through
          case 58: break;
          case 11:
            { echo (); return new Token (Symbol . SLASH);
            }
            // fall through
          case 59: break;
          case 12:
            { echo (); return new Token (Symbol . INTEGER, yytext ());
            }
            // fall through
          case 60: break;
          case 13:
            { echo (); return new Token (Symbol . SEMICOLON);
            }
            // fall through
          case 61: break;
          case 14:
            { echo (); return new Token (Symbol . LT);
            }
            // fall through
          case 62: break;
          case 15:
            { echo (); return new Token (Symbol . EQ);
            }
            // fall through
          case 63: break;
          case 16:
            { echo (); return new Token (Symbol . GT);
            }
            // fall through
          case 64: break;
          case 17:
            { echo (); return new Token (Symbol . ID, yytext ());
            }
            // fall through
          case 65: break;
          case 18:
            { echo (); return new Token (Symbol . LCPAREN);
            }
            // fall through
          case 66: break;
          case 19:
            { echo (); return new Token (Symbol . RCPAREN);
            }
            // fall through
          case 67: break;
          case 20:
            { echo (); return new Token( Symbol . ANDCOMP);
            }
            // fall through
          case 68: break;
          case 21:
            { echo (); return new Token (Symbol . ASSIGN);
            }
            // fall through
          case 69: break;
          case 22:
            { echo (); return new Token (Symbol . LE);
            }
            // fall through
          case 70: break;
          case 23:
            { echo (); return new Token (Symbol . NE);
            }
            // fall through
          case 71: break;
          case 24:
            { echo (); return new Token (Symbol . GE);
            }
            // fall through
          case 72: break;
          case 25:
            { echo (); return new Token (Symbol . DO);
            }
            // fall through
          case 73: break;
          case 26:
            { echo (); return new Token (Symbol . IF);
            }
            // fall through
          case 74: break;
          case 27:
            { echo (); return new Token (Symbol . IDE, yytext ());
            }
            // fall through
          case 75: break;
          case 28:
            { echo (); return new Token (Symbol . END);
            }
            // fall through
          case 76: break;
          case 29:
            { echo (); return new Token (Symbol . ODD);
            }
            // fall through
          case 77: break;
          case 30:
            { echo (); return new Token (Symbol . VAR);
            }
            // fall through
          case 78: break;
          case 31:
            { echo (); return new Token (Symbol . CALL);
            }
            // fall through
          case 79: break;
          case 32:
            { echo (); return new Token( Symbol . CONS);
            }
            // fall through
          case 80: break;
          case 33:
            { echo (); return new Token( Symbol . ELSE);
            }
            // fall through
          case 81: break;
          case 34:
            { echo (); return new Token( Symbol . HEAD);
            }
            // fall through
          case 82: break;
          case 35:
            { echo (); return new Token( Symbol . MAIN);
            }
            // fall through
          case 83: break;
          case 36:
            { echo (); return new Token( Symbol . NULL);
            }
            // fall through
          case 84: break;
          case 37:
            { echo (); return new Token( Symbol . TAIL);
            }
            // fall through
          case 85: break;
          case 38:
            { echo (); return new Token (Symbol . THEN);
            }
            // fall through
          case 86: break;
          case 39:
            { echo (); return new Token (Symbol . BEGIN);
            }
            // fall through
          case 87: break;
          case 40:
            { echo (); return new Token (Symbol . CONST);
            }
            // fall through
          case 88: break;
          case 41:
            { echo (); return new Token( Symbol . PRINT);
            }
            // fall through
          case 89: break;
          case 42:
            { echo (); return new Token (Symbol . WHILE);
            }
            // fall through
          case 90: break;
          case 43:
            { echo (); return new Token (Symbol . SOURCE);
            }
            // fall through
          case 91: break;
          case 44:
            { echo (); return new Token (Symbol . STRING);
            }
            // fall through
          case 92: break;
          case 45:
            { echo (); return new Token (Symbol . FUNC);
            }
            // fall through
          case 93: break;
          case 46:
            { echo (); return new Token( Symbol . READLINE);
            }
            // fall through
          case 94: break;
          case 47:
            { echo (); return new Token (Symbol . PROC);
            }
            // fall through
          case 95: break;
          case 48:
            { echo (); return new Token( Symbol . ASINT);
            }
            // fall through
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
